version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: gomysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: goexpert 
      MYSQL_PASSWORD: root 
    ports:
      - 3306:3306